version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      PORT: 4000
      ARANGO_ROOT_PASSWORD: pwd
      DB_HOST: db-test
      DB_PORT: 8529
      DB_USERNAME: root
      DB_PASSWORD: pwd
    volumes:
      - ./src:/app/src

  db-test:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: pwd
